#ifndef JBK_ENGINE_SETTINGS_H
#define JBK_ENGINE_SETTINGS_H

#define PARANOIA 4

#define JBK_RENDERER_DIRECT3D9
//#define JBK_RENDERER_DIRECT3D10
//#define JBK_RENDERER_OPENGL

#define JBK_WIN32

#define JBK_MATH_XNAMATH

#define JBK_DIRECT_3D_11

#endif // JBK_ENGINE_SETTINGS_H