#include "d3dutils.h"

DXGI_FORMAT JBKD3DUtils_ConvertFormat(JBKShaderFormat format) {
	switch (format) {
	case JBK_FMT_X: return DXGI_FORMAT_R32_FLOAT;
	case JBK_FMT_XY: return DXGI_FORMAT_R32G32_FLOAT;
	case JBK_FMT_XYZ: return DXGI_FORMAT_R32G32B32_FLOAT;
	case JBK_FMT_XYZW: return DXGI_FORMAT_R32G32B32A32_FLOAT;
	case JBK_FMT_COLOR: return DXGI_FORMAT_R8G8B8A8_UNORM;
	}
	return DXGI_FORMAT_UNKNOWN;
}

D3D11_PRIMITIVE_TOPOLOGY JBKD3DUtils_ConvertPritmitiveType(JBKPrimitiveType primitiveType) {
	switch (primitiveType) {
	case JBK_PRIMITIVE_POINT_LIST: return D3D_PRIMITIVE_TOPOLOGY_POINTLIST;
	case JBK_PRIMITIVE_LINE_LIST: return D3D_PRIMITIVE_TOPOLOGY_LINELIST;
	case JBK_PRIMITIVE_LINE_STRIP: return D3D_PRIMITIVE_TOPOLOGY_LINESTRIP;
	case JBK_PRIMITIVE_TRIANGLE_LIST: return D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST;
	case JBK_PRIMITIVE_TRIANGLE_STRIP: return D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP;
	}
	return D3D_PRIMITIVE_TOPOLOGY_UNDEFINED;
}
