#ifndef JBK_PRIMITIVE_TYPE_H
#define JBK_PRIMITIVE_TYPE_H

typedef enum {
	JBK_PRIMITIVE_POINT_LIST,
	JBK_PRIMITIVE_LINE_LIST,
	JBK_PRIMITIVE_LINE_STRIP,
	JBK_PRIMITIVE_TRIANGLE_LIST,
	JBK_PRIMITIVE_TRIANGLE_STRIP
} JBKPrimitiveType;

#endif // JBK_PRIMITIVE_TYPE_H